import { Pause, Play, RotateCcw, X, CheckCircle2, AlertCircle, LoaderCircle, Clock3, FileCode2, BookOpen } from 'lucide-react';
import type { Branch, Job } from '../shared/types';
import { countText, dateText, jobNames, statusNames } from './api';
import { Empty } from './ui';

export function JobsPanel({ jobs, branches, onAction, busy, author, onOutputs, onWriting }: { jobs: Job[]; branches: Branch[]; onAction: (job: Job, action: string) => void; busy: boolean; author: boolean; onOutputs: (job: Job) => void; onWriting: (job: Job) => void }) {
  if (!jobs.length) return <Empty icon={<Clock3 size={30} />} title="任务会在这里留下足迹">开始导入、规划或生成后，可以查看进度和模型用量。关闭网页不会停止后台任务。</Empty>;
  return <div className="jobs-list">{jobs.map(job => <section className="job-card" key={job.id}><div className="row between"><div className="row"><span className={`job-icon ${job.status}`}>{job.status === 'running' ? <LoaderCircle size={19} className="spin" /> : job.status === 'completed' ? <CheckCircle2 size={19} /> : ['failed', 'stale'].includes(job.status) ? <AlertCircle size={19} /> : <Clock3 size={19} />}</span><div><strong>{job.purpose === 'compress-summary' ? '压缩剧情摘要候选' : jobNames[job.kind]}</strong><small>{branches.find(branch => branch.id === job.branchId)?.name || '故事线'} · {dateText(job.createdAt)}</small></div></div><span className={`status-pill ${job.status}`}>{statusNames[job.status]}</span></div><div className="progress-track"><div style={{ width: `${job.total ? Math.min(100, job.progress / job.total * 100) : 0}%` }} /></div><div className="row between"><p className="job-message">{job.message || statusNames[job.status]}{job.total > 0 ? `（${job.progress}/${job.total}）` : ''}</p><span className="hint">{job.usageEstimated ? "约 " : ""}{countText(job.inputTokens + job.outputTokens)} tokens{job.usageEstimated ? "（估算）" : ""}</span></div>{job.error && <div className="notice error">{job.error}</div>}<div className="job-actions row end wrap">{author && job.kind === 'generate' && <button className="button secondary small" disabled={busy} onClick={() => onWriting(job)}><BookOpen size={14} />{job.status === 'completed' ? '打开生成章节' : ['failed', 'cancelled', 'stale'].includes(job.status) ? '查看生成过程与正文' : '查看实时正文'}</button>}{author && <button className="button secondary small job-output-button" disabled={busy} onClick={() => onOutputs(job)}><FileCode2 size={14} />模型输出 / 手工修正</button>}{['queued', 'running'].includes(job.status) && <button className="button secondary small" disabled={busy} onClick={() => onAction(job, 'pause')}><Pause size={14} />暂停</button>}{job.status === 'paused' && <button className="button secondary small" disabled={busy} onClick={() => onAction(job, 'resume')}><Play size={14} />继续</button>}{job.status === 'failed' && <span className="job-retry-group"><span className="hint">重试会重新调用模型</span><button className="button secondary small" disabled={busy} onClick={() => onAction(job, 'retry')}><RotateCcw size={14} />重试</button></span>}{['queued', 'running', 'paused', 'failed'].includes(job.status) && <button className="button ghost small" disabled={busy} onClick={() => onAction(job, 'cancel')}><X size={14} />取消任务</button>}</div></section>)}</div>;
}
