import { useEffect, useState } from 'react';
import { Plus, Save, Sparkles, Trash2, LockKeyhole, Bookmark, EyeOff } from 'lucide-react';
import type { ChapterRef, Entity, Foreshadow, Outline } from '../shared/types';
import { Empty } from './ui';

export function PlanningPanel({ outline, foreshadows, chapters, entities, revisionId, busy, onOutline, onForeshadows, onPlan, onDirtyChange }: { outline: Outline; foreshadows: Foreshadow[]; chapters: ChapterRef[]; entities: Entity[]; revisionId: string; busy: boolean; onOutline: (outline: Outline, revision: string) => Promise<boolean>; onForeshadows: (foreshadows: Foreshadow[], revision: string) => Promise<boolean>; onPlan: () => void; onDirtyChange?: (dirty: boolean) => void }) {
  const [draftOutline, setDraftOutline] = useState<Outline>(structuredClone(outline)); const [draftForeshadows, setDraftForeshadows] = useState<Foreshadow[]>(structuredClone(foreshadows)); const [outlineDirty, setOutlineDirty] = useState(false); const [foreshadowsDirty, setForeshadowsDirty] = useState(false); const [baseOutline, setBaseOutline] = useState(revisionId); const [baseForeshadows, setBaseForeshadows] = useState(revisionId); const [tab, setTab] = useState<'outline' | 'foreshadows'>('outline');
  useEffect(() => { if (!outlineDirty) { setDraftOutline(structuredClone(outline)); setBaseOutline(revisionId); } if (!foreshadowsDirty) { setDraftForeshadows(structuredClone(foreshadows)); setBaseForeshadows(revisionId); } }, [outline, foreshadows, revisionId, outlineDirty, foreshadowsDirty]);
  useEffect(() => { onDirtyChange?.(outlineDirty || foreshadowsDirty); return () => onDirtyChange?.(false); }, [outlineDirty, foreshadowsDirty, onDirtyChange]);
  const updateOutline = (value: Outline) => { setDraftOutline(value); setOutlineDirty(true); };
  const updateForeshadows = (value: Foreshadow[]) => { setDraftForeshadows(value); setForeshadowsDirty(true); };
  const statuses: Record<Foreshadow['status'], string> = { planned: '计划中', planted: '已埋下', resolved: '已揭晓', abandoned: '已放弃' };
  return <section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">THE AUTHOR’S DESK</span><h2>大纲与伏笔</h2><p><EyeOff size={13} /> 这里的规划与答案，仅在作者视图中显示。</p></div><button className="button primary small" disabled={busy || outlineDirty || foreshadowsDirty} onClick={onPlan}><Sparkles size={15} />让 AI 规划</button></div><div className="underlined-tabs"><button className={tab === 'outline' ? 'active' : ''} onClick={() => setTab('outline')}>故事大纲{outlineDirty && ' · 未保存'}</button><button className={tab === 'foreshadows' ? 'active' : ''} onClick={() => setTab('foreshadows')}>伏笔手记 {draftForeshadows.length}{foreshadowsDirty && ' · 未保存'}</button></div>
    {tab === 'outline' ? <div className="form-stack planning-form"><label><span>粗大纲 <small>为故事提供方向，允许随发展调整</small></span><textarea rows={7} placeholder="故事从哪里开始，会经过怎样的转折，最终去向何方？" value={draftOutline.coarse} onChange={e => updateOutline({ ...draftOutline, coarse: e.target.value })} /></label><label><span className="row"><LockKeyhole size={14} />不可改变的设定</span><textarea rows={3} placeholder="例如：主角不会复活；魔法必须付出代价。" value={draftOutline.locked} onChange={e => updateOutline({ ...draftOutline, locked: e.target.value })} /></label><div className="row between"><h3>滚动细纲</h3><button className="button secondary small" onClick={() => updateOutline({ ...draftOutline, fine: [...draftOutline.fine, { chapter: Math.max(chapters.length, ...draftOutline.fine.map(f => f.chapter)) + 1, title: '', goal: '' }] })}><Plus size={14} />添加章节规划</button></div>{draftOutline.fine.map((fine, index) => <div className="fine-outline" key={index}><div className="fine-number">第<input aria-label="章节序号" type="number" min={1} value={fine.chapter} onChange={e => updateOutline({ ...draftOutline, fine: draftOutline.fine.map((f, i) => i === index ? { ...f, chapter: Number(e.target.value) } : f) })} />章</div><div className="form-stack"><input aria-label="规划章节标题" placeholder="章节标题" value={fine.title} onChange={e => updateOutline({ ...draftOutline, fine: draftOutline.fine.map((f, i) => i === index ? { ...f, title: e.target.value } : f) })} /><textarea aria-label="本章目标" rows={3} placeholder="这一章要发生什么？哪些人物或伏笔应当推进？" value={fine.goal} onChange={e => updateOutline({ ...draftOutline, fine: draftOutline.fine.map((f, i) => i === index ? { ...f, goal: e.target.value } : f) })} /></div><button className="icon-button danger-text" aria-label="删除章节规划" onClick={() => updateOutline({ ...draftOutline, fine: draftOutline.fine.filter((_, i) => i !== index) })}><Trash2 size={16} /></button></div>)}<button className="button primary align-start" disabled={busy || !outlineDirty} onClick={async () => { if (await onOutline(draftOutline, baseOutline)) setOutlineDirty(false); }}><Save size={16} />保存大纲</button></div> : <div className="form-stack planning-form"><div className="row between"><p className="muted">没被揭晓的线索，会继续留在这里。</p><button className="button secondary small" onClick={() => updateForeshadows([...draftForeshadows, { id: crypto.randomUUID(), title: '', detail: '', status: 'planned', revealCondition: '', relatedEntityIds: [] }])}><Plus size={14} />记录伏笔</button></div>{!draftForeshadows.length && <Empty icon={<Bookmark size={29} />} title="把未说出口的秘密留在这里">伏笔可以由创作过程自动记录，也可以手动添加。阅读正文时不会展示这些内容。</Empty>}{draftForeshadows.map((item, index) => {
      const update = (patch: Partial<Foreshadow>) => updateForeshadows(draftForeshadows.map((f, i) => i === index ? { ...f, ...patch } : f));
      return <article className="foreshadow-card form-stack" key={item.id}><div className="row"><Bookmark size={18} /><input aria-label="伏笔标题" placeholder="这个伏笔叫什么？" value={item.title} onChange={e => update({ title: e.target.value })} /><select aria-label="伏笔状态" value={item.status} onChange={e => update({ status: e.target.value as Foreshadow['status'] })}>{Object.entries(statuses).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select><button className="icon-button danger-text" aria-label="删除伏笔" onClick={() => updateForeshadows(draftForeshadows.filter(f => f.id !== item.id))}><Trash2 size={16} /></button></div><label>隐藏的真相<textarea rows={3} value={item.detail} onChange={e => update({ detail: e.target.value })} placeholder="表面发生了什么，真正的原因是什么？" /></label><label>揭晓条件<input value={item.revealCondition} onChange={e => update({ revealCondition: e.target.value })} placeholder="什么发生时，读者应知道答案？" /></label><div className="form-grid"><label>计划揭晓章节<input type="number" min={1} value={item.dueChapter ?? ''} placeholder="可不指定" onChange={e => update({ dueChapter: e.target.value ? Number(e.target.value) : undefined })} /></label><label>埋设位置<select value={item.plantedChapterId || ''} onChange={e => update({ plantedChapterId: e.target.value || undefined })}><option value="">尚未指定</option>{chapters.map(ch => <option key={ch.id} value={ch.id}>{ch.title}</option>)}</select></label><label>揭晓位置<select value={item.resolvedChapterId || ''} onChange={e => update({ resolvedChapterId: e.target.value || undefined })}><option value="">尚未揭晓</option>{chapters.map(ch => <option key={ch.id} value={ch.id}>{ch.title}</option>)}</select></label><label>关联人物 / 资料<select multiple value={item.relatedEntityIds} onChange={e => update({ relatedEntityIds: Array.from(e.target.selectedOptions, option => option.value) })}>{entities.filter(e => !e.mergedInto).map(entity => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select><span className="hint">按住 Ctrl / ⌘ 可多选。</span></label></div></article>;
    })}<button className="button primary align-start" disabled={busy || !foreshadowsDirty || draftForeshadows.some(f => !f.title.trim())} onClick={async () => { if (await onForeshadows(draftForeshadows, baseForeshadows)) setForeshadowsDirty(false); }}><Save size={16} />保存伏笔手记</button></div>}
  </section>;
}
