import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, CheckCircle2, CircleSlash, ImagePlus, Images, RefreshCw, Trash2, WandSparkles, X } from 'lucide-react';
import type { ChapterRef, Entity, ImageGenerateInput, StoryImage, StoryImageKind } from '../shared/types';
import { dateText, statusNames } from './api';
import { Empty, Modal, Notice } from './ui';
import { ImageViewer } from './ImageViewer';

export type ImageTarget = Omit<ImageGenerateInput, 'baseRevisionId'>;
export type ImageAction = 'retry' | 'cancel' | 'activate' | 'deactivate' | 'delete';
export const imageKindNames: Record<StoryImageKind, string> = { portrait: '人物立绘', cg: '剧情 CG', entity: '资料图片', map: '世界地图' };
export function latestImage(images: StoryImage[], entityId: string) { return images.filter(image => image.entityId === entityId && image.active !== false && image.status === 'completed' && image.url).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0]; }

export function ImageRequestDialog({ target, title, excerpt, reference, busy, error, onClose, onSubmit }: { target: ImageTarget; title: string; excerpt?: string; reference?: StoryImage; busy: boolean; error: string; onClose: () => void; onSubmit: (input: ImageTarget) => Promise<void> }) {
  const [instruction, setInstruction] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (reference && !instruction.trim()) return; await onSubmit({ ...target, instruction: instruction.trim() || undefined }); }
  return <Modal title={title} onClose={() => !busy && onClose()} closeDisabled={busy}><form className="form-stack image-request" onSubmit={submit}>{reference?.url && <img className="image-reference" src={reference.url} alt={`修改参考：${reference.title}`} />}{excerpt && <blockquote className="image-source-text">{excerpt}</blockquote>}<p className="hint">{reference ? '以这张图片为参考，AI 先根据修改要求编写专用提示词，再生成新图片。原图会保留。' : 'AI 根据已保存的正文或资料编写专用提示词，再生成图片。已有图片会保留，完成后可在图册查看本次提示词、尺寸与人物参考。'}</p><label>{reference ? '修改要求' : '补充绘制要求（可选）'}<textarea rows={4} required={!!reference} value={instruction} onChange={event => setInstruction(event.target.value)} placeholder={reference ? '例如：保留服装和五官，把背景改成雨中的城门。' : '例如：全身立绘、简洁背景，或希望表现的光线与构图。'} /></label>{error && <Notice error={error} />}<button className="button primary" disabled={busy || (!!reference && !instruction.trim())}><ImagePlus size={16} />{busy ? '正在提交…' : reference ? '开始修改' : '开始绘制'}</button></form></Modal>;
}

export function ImageGenerationDetails({ image }: { image: StoryImage }) {
  const parameters = image.generationParameters; const characters = image.referenceCharacters || [];
  const labels: Record<string, string> = { protocol: '图片接口', model: '图片模型', quality: '生成质量', systemInstruction: '图片模型系统提示词', temperature: 'Temperature', topP: 'Top P', topK: 'Top K', seed: '随机种子', maxOutputTokens: '最大输出 Token', thinkingLevel: '思考等级', includeThoughts: '返回思考内容', searchGrounding: 'Google 搜索', outputFormat: '输出格式', outputCompression: '压缩质量', background: '图片背景', inputFidelity: '参考图保真度', moderation: '内容审核', negativePrompt: '负面提示词', steps: '采样步数', guidanceScale: '提示词引导强度', promptUpsampling: '供应商增强提示词', disableSafetyChecker: '关闭供应商安全检查' };
  const showValue = (key: string, value: unknown) => typeof value === 'boolean' ? value ? '开启' : '关闭' : key === 'protocol' ? ({ 'openai-images': 'OpenAI Images', gemini: 'Gemini', 'together-images': 'Together' } as Record<string, string>)[String(value)] || String(value) : String(value);
  return <div className="image-generation-details form-stack"><section><h3>{image.promptStatus === 'completed' ? 'AI 优化后的生图提示词' : image.promptStatus === 'pending' ? '生图提示词尚未完成' : '绘图提示词（历史记录）'}</h3>{image.promptStatus === 'pending' ? <p className="hint">提示词优化完成后，会保存实际发送给图片模型的提示词与参数。</p> : image.prompt ? <pre className="image-optimized-prompt" data-testid="optimized-image-prompt">{image.prompt}</pre> : <p className="hint">此记录没有已完成的绘图提示词。</p>}{image.optimizedAt && <small>优化完成于 {dateText(image.optimizedAt)}</small>}</section>{parameters && <section><h3>本次图片参数</h3><dl className="image-actual-parameters" data-testid="image-actual-parameters">{parameters.size && <><dt>图片尺寸</dt><dd>{parameters.size.replace('x', ' × ')}</dd></>}{parameters.aspectRatio && <><dt>画幅比例</dt><dd>{parameters.aspectRatio}</dd></>}{parameters.imageSize && <><dt>图片分辨率</dt><dd>{parameters.imageSize}</dd></>}{parameters.width && parameters.height && <><dt>宽 × 高</dt><dd>{parameters.width} × {parameters.height}</dd></>}{Object.entries(parameters).filter(([key, value]) => key in labels && value !== undefined && value !== '').map(([key, value]) => <div className="image-parameter-row" key={key}><dt>{labels[key]}</dt><dd>{showValue(key, value)}</dd></div>)}</dl></section>}<section className="image-character-references"><h3>本次人物参考</h3>{characters.length ? <ul>{characters.map(character => <li key={`${character.entityId}:${character.imageId}`}><span>{character.name}</span><small>已完成立绘</small></li>)}</ul> : <p className="hint">本次没有使用人物立绘参考图。</p>}{image.referenceImageId && <p className="hint">此次 AI 修改同时参考了原图。</p>}</section></div>;
}

function ImageUseControls({ image, busy, onAction }: { image: StoryImage; busy: boolean; onAction?: (image: StoryImage, action: ImageAction) => void }) {
  if (!onAction) return null;
  return <>{image.status === 'completed' && <button className="text-button" disabled={busy} onClick={() => onAction(image, image.active === false ? 'activate' : 'deactivate')}>{image.active === false ? <CheckCircle2 size={13} /> : <CircleSlash size={13} />}{image.active === false ? '启用图片' : '停用图片'}</button>}<button className="text-button danger-text" disabled={busy} onClick={() => onAction(image, 'delete')}><Trash2 size={13} />删除图片</button></>;
}

export function StoryImageCards({ images, author = false, busy = false, onGenerate, onAction, onChapter, onEntity, compact = false }: { images: StoryImage[]; author?: boolean; busy?: boolean; onGenerate?: (target: ImageTarget) => void; onAction?: (image: StoryImage, action: ImageAction) => void; onChapter?: (image: StoryImage) => void; onEntity?: (id: string) => void; compact?: boolean }) {
  const [opened, setOpened] = useState<{ id: string; detailsOpen: boolean } | null>(null);
  const listed = author ? images : images.filter(image => image.active !== false);
  const current = opened && listed.find(image => image.id === opened.id);
  useEffect(() => { if (opened && !images.some(image => image.id === opened.id)) setOpened(null); }, [opened?.id, images]);
  const viewerAction = (image: StoryImage, action: ImageAction) => { if (action === 'activate' || action === 'deactivate') setOpened(null); onAction?.(image, action); };
  return <><div className={`story-image-grid ${compact ? 'compact' : ''}`}>{listed.map(image => <article className={`story-image-card image-kind-${image.kind}`} key={image.id} data-image-id={image.id} data-image-active={image.active !== false}>
    <button className="story-image-preview" disabled={!image.url || image.status !== 'completed'} onClick={() => setOpened({ id: image.id, detailsOpen: false })} aria-label={`查看图片 ${image.title}`}>{image.status === 'completed' && image.url ? <img src={image.url} alt={image.title} loading="lazy" /> : <span><Images size={28} className={image.status === 'running' ? 'spin' : ''} /><small>{author && image.status === 'running' && image.promptStatus === 'pending' ? '正在优化绘图提示词' : statusNames[image.status]}</small></span>}</button>
    <div className="story-image-info"><div className="row between"><span>{imageKindNames[image.kind]}</span><span className={`status-pill ${image.status}`}>{statusNames[image.status]}</span></div><h4>{image.title}</h4>{image.error && author && <p className="image-error" role="alert">{image.error}</p>}{image.status === 'paused' && author && <p className="hint">任务中断，重新绘制会发起新的生图请求。</p>}{author && image.status === 'completed' && <span className={`image-selection-pill ${image.active === false ? 'is-inactive' : 'is-active'}`}>{image.active === false ? '未启用 · 暂存' : '已启用'}</span>}<small>{dateText(image.createdAt)}{image.automatic ? ' · 自动绘制' : ''}{author && image.visibility === 'secret' ? ' · 仅作者可见' : ''}</small>
      <div className="story-image-actions">
        {image.chapterId && onChapter && <button className="text-button" onClick={() => onChapter(image)}>关联剧情<ArrowUpRight size={12} /></button>}{image.entityId && onEntity && <button className="text-button" onClick={() => onEntity(image.entityId!)}>关联资料<ArrowUpRight size={12} /></button>}
        {author && <><button className="text-button" onClick={() => setOpened({ id: image.id, detailsOpen: true })}>生图详情<ArrowUpRight size={12} /></button><ImageUseControls image={image} busy={busy} onAction={onAction} />{image.status === 'completed' && onGenerate && <><button className="text-button" disabled={busy} onClick={() => onGenerate({ kind: image.kind, entityId: image.entityId, chapterId: image.chapterId, selection: image.selection })}><RefreshCw size={12} />重新绘制</button><button className="text-button" disabled={busy || image.active === false} onClick={() => onGenerate({ kind: image.kind, entityId: image.entityId, chapterId: image.chapterId, selection: image.selection, referenceImageId: image.id })}><WandSparkles size={12} />{image.active === false ? '启用后可修改' : 'AI 修改'}</button></>}{onAction && ['failed', 'paused', 'stale'].includes(image.status) && <button className="text-button" disabled={busy} onClick={() => onAction(image, 'retry')}><RefreshCw size={12} />{image.status === 'paused' ? '恢复绘制' : '重试绘制'}</button>}{onAction && ['queued', 'running'].includes(image.status) && <button className="text-button" disabled={busy} onClick={() => onAction(image, 'cancel')}><X size={12} />取消绘制</button>}</>}
      </div>
    </div>
  </article>)}</div>{current && (author || current.url && current.status === 'completed') && <ImageViewer key={current.id} image={current} initialDetailsOpen={opened?.detailsOpen} detailsLabel={author ? '生图详情' : '关联剧情'} onClose={() => setOpened(null)}>{(author || current.chapterId && onChapter) && <>{author && <><div className="story-image-actions viewer-image-actions"><ImageUseControls image={current} busy={busy} onAction={onAction ? viewerAction : undefined} />{current.status === 'completed' && <span className={`image-selection-pill ${current.active === false ? 'is-inactive' : 'is-active'}`}>{current.active === false ? '未启用 · 暂存' : '已启用'}</span>}</div><ImageGenerationDetails image={current} /></>}{author && current.sourceText && <blockquote className="image-source-text">{current.sourceText}</blockquote>}{current.chapterId && onChapter && <button className="button secondary small" onClick={() => { setOpened(null); onChapter(current); }}>查看关联剧情<ArrowUpRight size={13} /></button>}</>}</ImageViewer>}</>;
}
export function ImageGallery({ images, entities, chapters, author, busy, onGenerate, onAction, onChapter, onEntity }: { images: StoryImage[]; entities: Entity[]; chapters: ChapterRef[]; author: boolean; busy: boolean; onGenerate: (target: ImageTarget) => void; onAction: (image: StoryImage, action: ImageAction) => void; onChapter: (image: StoryImage) => void; onEntity: (id: string) => void }) {
  const [filter, setFilter] = useState<StoryImageKind | 'all'>('all'); const [search, setSearch] = useState('');
  const filtered = images.filter(image => (filter === 'all' || image.kind === filter) && [image.title, entities.find(entity => entity.id === image.entityId)?.name || '', chapters.find(chapter => chapter.id === image.chapterId)?.title || ''].join(' ').toLowerCase().includes(search.toLowerCase()));
  return <section className="data-panel image-gallery"><div className="panel-heading"><div><span className="eyebrow">STORY GALLERY</span><h2>故事图册</h2><p>查看当前故事线的立绘、剧情 CG、资料图片和地图；图片保留与剧情及资料的关联。</p></div></div><div className="world-tools"><div className="filter-chips"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>全部 {images.length}</button>{Object.entries(imageKindNames).map(([kind, name]) => <button key={kind} className={filter === kind ? 'active' : ''} onClick={() => setFilter(kind as StoryImageKind)}>{name} {images.filter(image => image.kind === kind).length}</button>)}</div><label className="search-input"><input aria-label="查找故事图片" value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索图片、人物或章节…" /></label></div>{filtered.length ? <StoryImageCards images={filtered} author={author} busy={busy} onGenerate={onGenerate} onAction={onAction} onChapter={onChapter} onEntity={onEntity} /> : <Empty icon={<Images size={30} />} title={images.length ? '没有匹配的图片' : '故事图册尚未展开'}>{images.length ? '切换分类，或用人物、章节名称查找。' : author ? '在正文生成剧情 CG，或在世界资料里为人物与其他资料绘制图片。' : '图片完成并公开后，会显示在这里。'}</Empty>}</section>;
}
